# Generated by Django 4.1.4 on 2023-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(max_length=15)),
                ('husband_age', models.CharField(max_length=15)),
                ('husband_religion', models.CharField(max_length=15)),
                ('husband_aadhar', models.CharField(max_length=15)),
                ('wife_name', models.CharField(max_length=15)),
                ('wife_age', models.CharField(max_length=15)),
                ('wife_religion', models.CharField(max_length=15)),
                ('wife_aadhar', models.CharField(max_length=15)),
                ('witness_name', models.CharField(max_length=15)),
                ('witness_gender', models.CharField(max_length=15)),
                ('witness_age', models.CharField(max_length=15)),
                ('witness_email', models.CharField(max_length=15)),
                ('witness_aadhar', models.CharField(max_length=15)),
                ('email_husband_or_wife', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
            ],
        ),
    ]
