# Generated by Django 4.1.4 on 2023-01-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_rename_email_husband_or_wife_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
