# Generated by Django 4.1.4 on 2023-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_remove_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
